//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AccountDetails = new HashSet<AccountDetail>();
        }
    
        public System.Guid Id { get; set; }
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public string DocType { get; set; }
        public string Canceled { get; set; }
        public string Printed { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string Address { get; set; }
        public string DocCur { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public Nullable<decimal> DocumentTotal { get; set; }
        public Nullable<decimal> DocumentTotalFC { get; set; }
        public string Remark { get; set; }
        public string PaymentNumber { get; set; }
        public string CashAccount { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<decimal> CashAmountFC { get; set; }
        public string TransferAccount { get; set; }
        public Nullable<decimal> TransferAmount { get; set; }
        public Nullable<decimal> TransferAmountFC { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string IntendedPurpose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountDetail> AccountDetails { get; set; }
    }
}
