//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public int DocNum { get; set; }
        public int RowNumber { get; set; }
        public string AccountCode { get; set; }
        public string Description { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> GrossAmountFC { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
