//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdEntities : DbContext
    {
        public IdEntities()
            : base("name=IdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountDetail> AccountDetails { get; set; }
        public virtual DbSet<AccountPayment> AccountPayments { get; set; }
        public virtual DbSet<ARInvoice> ARInvoices { get; set; }
        public virtual DbSet<ARInvoiceDetail> ARInvoiceDetails { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DeliveryOrder> DeliveryOrders { get; set; }
        public virtual DbSet<DeliveryOrderDetail> DeliveryOrderDetails { get; set; }
        public virtual DbSet<GoodReceiptPO> GoodReceiptPOes { get; set; }
        public virtual DbSet<GoodReceiptPODetail> GoodReceiptPODetails { get; set; }
        public virtual DbSet<InventoryTransfer> InventoryTransfers { get; set; }
        public virtual DbSet<InventoryTransferDetail> InventoryTransferDetails { get; set; }
        public virtual DbSet<InventoryTransferRequest> InventoryTransferRequests { get; set; }
        public virtual DbSet<InventoryTransferRequestDetail> InventoryTransferRequestDetails { get; set; }
        public virtual DbSet<MasterCustomer> MasterCustomers { get; set; }
        public virtual DbSet<MasterCustomerContact> MasterCustomerContacts { get; set; }
        public virtual DbSet<MasterItem> MasterItems { get; set; }
        public virtual DbSet<MasterVendor> MasterVendors { get; set; }
        public virtual DbSet<MasterVendorContact> MasterVendorContacts { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
    }
}
