//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterCustomer()
        {
            this.MasterCustomerContacts = new HashSet<MasterCustomerContact>();
        }
    
        public System.Guid Id { get; set; }
        public string BPCode { get; set; }
        public string BPName { get; set; }
        public string ForeignName { get; set; }
        public string BPType { get; set; }
        public Nullable<int> GroupCode { get; set; }
        public string BPCurrency { get; set; }
        public Nullable<int> PriceListNo { get; set; }
        public string FederalTaxId { get; set; }
        public string IdNo2 { get; set; }
        public int SalesEmployeeCode { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string FaxNumber { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public string Inactive { get; set; }
        public Nullable<System.DateTime> InactiveFrom { get; set; }
        public Nullable<System.DateTime> InactiveTo { get; set; }
        public string LimitTempo { get; set; }
        public string Area { get; set; }
        public string Branch { get; set; }
        public string AccountReceivable { get; set; }
        public string TaxGroup { get; set; }
        public int PaymentTermsCode { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> PayableLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterCustomerContact> MasterCustomerContacts { get; set; }
    }
}
