//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SalesOrderDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SalesOrderId { get; set; }
        [Display(Name = "Internal Number")]
        public int DocEntry { get; set; }
        [Display(Name = "RowNumber")]
        public int RowNumber { get; set; }
        [Display(Name = "Target Document Type")]
        public int TargetType { get; set; }

        public Nullable<int> TargetEntry { get; set; }
        public string BaseRef { get; set; }
        public int BaseType { get; set; }
        public int BaseEntry { get; set; }
        public int BaseLine { get; set; }
        public string RowStatus { get; set; }

        [Display(Name = "Item No")]
        public string ItemCode { get; set; }
        [Display(Name = "Item Description")]
        public string Description { get; set; }
        [Display(Name = "Part Number")]
        public string PartNumber { get; set; }
        [Display(Name = "Inventory UoM")]
        public string InventoryUoM { get; set; }
        [Display(Name = "Quantity")]
        public Nullable<decimal> Quantity { get; set; }

        public Nullable<decimal> InventoryUoMQuantity { get; set; }
        [Display(Name = "Warehouse")]
        public string WarehouseCode { get; set; }
        [Display(Name = "Ship Date")]
        public Nullable<System.DateTime> ShipDate { get; set; }
        [Display(Name = "Remaining Open Qty")]
        public Nullable<decimal> OpenQuantity { get; set; }
        [Display(Name = "Distribution Rule")]
        public string OcrCode { get; set; }
        [Display(Name = "Distribution Rule2")]
        public string OcrCode2 { get; set; }
        [Display(Name = "Unit Price")]
        public Nullable<decimal> UnitPrice { get; set; }
        [Display(Name = "Discount per Row")]
        public Nullable<decimal> DiscountPercent { get; set; }

        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> RowTotal { get; set; }
        public Nullable<decimal> RowTotalFC { get; set; }
        public string AccountCode { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
