//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrder()
        {
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
        }
    
        public System.Guid Id { get; set; }
        [Display(Name = "Internal Number")]
        public int DocEntry { get; set; }

        [Display(Name = "Customer Code")]
        public string CardCode { get; set; }

        [Display(Name = "Customer Name")]
        public string CardName { get; set; }

        [Display(Name = "No.")]
        public int DocNum { get; set; }
        [Display(Name = "BP Reference No.")]
        public string NumAtCard { get; set; }

        [Display(Name = "Posting Date")]
        public Nullable<System.DateTime> DocDate { get; set; }

        [Display(Name = "Due Date")]
        public Nullable<System.DateTime> DocDueDate { get; set; }
        [Display(Name = "Document Type")]
        public string DocType { get; set; }
        public string Printed { get; set; }

        [Display(Name = "Status")]
        public string DocStatus { get; set; }

        [Display(Name = "Currency")]
        public string DocCur { get; set; }

        public Nullable<decimal> DocRate { get; set; }

        [Display(Name = "Sales Order No.")]
        public string SalesOrderNo { get; set; }
        public Nullable<int> GroupNum { get; set; }
        [Display(Name = "Sales Employee")]
        public int SalesEmployee { get; set; }

        [Display(Name = "Contact Person")]
        public Nullable<int> ContactPerson { get; set; }

        [Display(Name = "Ship To")]
        public string ShipTo { get; set; }

        [Display(Name = "Bill To")]
        public string BillTo { get; set; }

        [Display(Name = "Tax Rate")]
        public Nullable<decimal> TaxRate { get; set; }
        [Display(Name = "Total Tax")]
        public Nullable<decimal> TotalTax { get; set; }
        [Display(Name = "Tax Amount (FC)")]
        public Nullable<decimal> TaxAmountFC { get; set; }
        [Display(Name = "Discount For Document")]
        public Nullable<decimal> DiscountForDocument { get; set; }
        [Display(Name = "Total Discount")]
        public Nullable<decimal> TotalDiscount { get; set; }
        [Display(Name = "Total Discount (FC)")]
        public Nullable<decimal> TotalDiscountFC { get; set; }
        [Display(Name = "Document Total")]
        public Nullable<decimal> DocumentTotal { get; set; }
        [Display(Name = "Document Total (FC)")]
        public Nullable<decimal> DocumentTotalFC { get; set; }
        [Display(Name = "Paid to Date")]
        public Nullable<decimal> PaidToDate { get; set; }
        [Display(Name = "Paid (FC)")]
        public Nullable<decimal> PaidFC { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
    }
}
